name: supabase_flutter
description: Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
version: 0.2.12
homepage: "https://supabase.io"
repository: "https://github.com/supabase/supabase-flutter"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.6
  supabase: ^0.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
